### ISSUE TITLE
internal server error 500

### ISSUE THREAD

**Issue by meijer-jeroen** [refresh-bio/vclust#5]
Hi, when I tried the Vclust server in the last couple of days I got an internal server error 500. The job id is friendly-virulence-d77

**Comment by aziele** [comment]
Hi,

Thank you for reporting this issue. We are still working on the web service and thus we apologize for this inconvenience.

The error you reported is caused by three sequences in your input FASTA file, each with a duplicate ID. To address this issue, we have just improved the validation of input data in the Vclust's form. Now, if your FASTA file contains sequences with duplicate IDs, the server will report these duplicated IDs upon file upload. This will allow you to manually remove or modify the duplicate IDs in the FASTA file before proceeding with the analysis. Once the FASTA input file no longer contains repeated IDs, the web service will start the analysis and return the results.

Best,
Andrzej

**Comment by meijer-jeroen** [comment]
thanks!
